import { data } from "autoprefixer";
import axios from "axios";
import Head from "next/head";
import { useEffect } from "react";
import Banner from "../components/Banner";
import Header from "../components/Header";
import MediumCard from "../components/MediumCard";
import OptionTabs from "../components/OptionTabs";
import SmallCard from "../components/SmallCard";

export default function Home({ exploreData, cardData }) {
  const API_URL = "http://localhost:8040/ecommerce-floor/user/1.0.0/user";
  const userId = "1666677607588367";

  useEffect(() => {
    const fetchData = async () => {
      try {
        const userData = await axios.get(`${API_URL}/${userId}`);
        console.log(userData);
      } catch (err) {
        console.log(err);
      }
    };
    fetchData();
  });

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />
      {/* <OptionTabs /> */}
      {/* Header */}
      {/* Header */}
      <Banner />
      {/* Header */}
      <main className="max-w-[1000px] mx-auto px-8 md:px-16">
        <section className="pt-6">
          <h2 className="section-title">Explore</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData?.map(({ img, distance, location }) => (
              <SmallCard
                img={img}
                key={img}
                distance={distance}
                location={location}
              />
            ))}
          </div>
        </section>
        <section className="pt-6">
          <h className="section-title py-10">Live anywhere</h>
          <div
            className="flex space-x-3 overflow-scroll scrollbar-hide
          p-3 -ml-3"
          >
            {cardData?.map(({ img, title }) => (
              <MediumCard key={title} img={img} title={title} />
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}
export async function getStaticProps() {
  const exploreData = await fetch("https://www.jsonkeeper.com/b/4G1G").then(
    (res) => res.json()
  );
  const cardData = await fetch("https://www.jsonkeeper.com/b/VHHT").then(
    (res) => res.json()
  );
  return {
    props: {
      exploreData,
      cardData,
    },
  };
}
